### ISSUE TITLE
Crashes when used with Dist::Zilla::Plugin::FatPacker due to Compiler::Lexer

### ISSUE THREAD

**Issue by xsawyerx** [Leont/dist-zilla-plugin-minimumperlfast#4]
`Compiler::Lexer` has a [bug](https://github.com/goccy/p5-Compiler-Lexer/issues/77) which is triggered when this plugin is used along with `Dist::Zilla::Plugin::FatPacker` ([correlating bug report](https://github.com/doherty/Dist-Zilla-Plugin-FatPacker/issues/5)).

`Compiler::Lexer` does not seem maintained (no code changes or releases for over 2 years), but I do believe this might be fixed by the way either this plugin or `FatPacker` plugin is implemented, which probably trigger each other by accident.

**Comment by Leont** [comment]
I don't know enough about `Compiler::Lexer`s internals to say anything about what's going on. A backtrace may be helpful though.

Does the same thing happen when running `Perl::MinimumVersion::Fast` on the fatpacked file? In that case it's not my plugin that's at fault (). The most logical explanation would be that it pukes over some unusual input, in which case knowing what module it trips over would be useful knowledge. I'm not sure if there's a more efficient way of figuring this out than trial-and-error.

**Comment by xsawyerx** [comment]
This is not a bug with the plugin, but with `Compiler::Lexer` which can be verified regardless of this plugin or `Perl::MinimumVersion::Fast`.

Feel free to close the bug if you think it's irrelevant to note.

**Comment by Code-Hex** [comment]
Hello, @xsawyerx @Leont 
While exchanging of opinions with the author at the backside, I'm trying now to contribute to [`Compiler::Lexer`](https://github.com/goccy/p5-Compiler-Lexer/pull/81).
It will be helpful if you let me know what content of a file you loaded to `Compiler::Lexer`.

Thanks.

**Comment by xsawyerx** [comment]
I cannot recreate the failure so I'm closing all related issues.
